import mongoose from "mongoose"
import dotenv from "dotenv"
import path from "path"
import { fileURLToPath } from "url"
import User from "../models/User.js"
import Course from "../models/Course.js"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
dotenv.config({ path: path.resolve(__dirname, "../.env") })

// Course data based on categories
const courseData = [
  // Class 9
  {
    title: "Class 9 - Mathematics",
    category: "Class 9",
    subcategory: "Mathematics",
    description:
      "Complete mathematics course for Class 9 including Algebra, Geometry, and Trigonometry. Learn fundamental concepts that form the foundation for higher mathematics.",
    price: 1,
    duration: "12 weeks",
    courseLevel: "Beginner",
    prerequisites: "Class 8 Mathematics",
    whatYouWillLearn: [
      "Polynomial and Algebraic expressions",
      "Linear equations in one and two variables",
      "Coordinate geometry basics",
      "Triangles and congruence",
      "Circles and their properties",
      "Surface area and volume",
      "Statistics and probability",
    ],
    curriculum: [
      {
        module: "Algebra Fundamentals",
        topics: ["Polynomials", "Algebraic Identities", "Factorization", "Linear Equations"],
      },
      { module: "Geometry", topics: ["Triangles", "Circles", "Constructions", "Coordinate Geometry"] },
      { module: "Trigonometry", topics: ["Introduction to Trigonometry", "Trigonometric Ratios", "Applications"] },
      { module: "Statistics", topics: ["Data Representation", "Mean, Median, Mode", "Probability Basics"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 9 - Science",
    category: "Class 9",
    subcategory: "Science",
    description:
      "Comprehensive science course covering Physics, Chemistry, and Biology for Class 9. Understand the fundamental concepts of natural sciences.",
    price: 1999,
    duration: "12 weeks",
    courseLevel: "Beginner",
    prerequisites: "Class 8 Science",
    whatYouWillLearn: [
      "Matter and its states",
      "Atomic structure",
      "Chemical reactions and equations",
      "Motion and forces",
      "Work, energy and power",
      "Cell structure and organization",
      "Diversity in living organisms",
    ],
    curriculum: [
      { module: "Physics", topics: ["Motion", "Forces", "Work and Energy", "Sound", "Light"] },
      { module: "Chemistry", topics: ["Matter", "Atoms and Molecules", "Chemical Reactions", "Acids and Bases"] },
      { module: "Biology", topics: ["Cell", "Tissues", "Organisms", "Reproduction", "Genetics Basics"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 9 - English",
    category: "Class 9",
    subcategory: "English",
    description:
      "English language and literature course for Class 9. Improve reading, writing, and comprehension skills.",
    price: 999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic English Knowledge",
    whatYouWillLearn: [
      "Grammar and sentence structure",
      "Reading comprehension",
      "Essay writing",
      "Literature analysis",
      "Communication skills",
      "Vocabulary enhancement",
    ],
    curriculum: [
      { module: "Grammar", topics: ["Parts of Speech", "Tenses", "Sentence Construction"] },
      { module: "Literature", topics: ["Poetry", "Prose", "Drama", "Short Stories"] },
      { module: "Writing Skills", topics: ["Essay Writing", "Letter Writing", "Report Writing"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 9 - Hindi",
    category: "Class 9",
    subcategory: "Hindi",
    description: "Hindi language and literature course for Class 9. Master Hindi grammar and literature.",
    price: 999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic Hindi Knowledge",
    whatYouWillLearn: [
      "Hindi grammar and syntax",
      "Kavya and literature analysis",
      "Essay writing in Hindi",
      "Vocabulary and comprehension",
      "Communication in Hindi",
    ],
    curriculum: [
      { module: "Grammar", topics: ["Sangya", "Sarvanaam", "Kriya", "Karak"] },
      { module: "Literature", topics: ["Kavya", "Gaddya", "Drama"] },
      { module: "Writing", topics: ["Patra Lekhan", "Nibandh", "Varna Vichar"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // Class 10
  {
    title: "Class 10 - Mathematics",
    category: "Class 10",
    subcategory: "Mathematics",
    description:
      "Complete mathematics course for Class 10 board exams. Master all CBSE syllabus topics with board exam strategies.",
    price: 2499,
    duration: "16 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 9 Mathematics",
    whatYouWillLearn: [
      "Real numbers and polynomials",
      "Quadratic equations",
      "Arithmetic and geometric progressions",
      "Coordinate geometry",
      "Triangles and trigonometry",
      "Circles and constructions",
      "Areas and volumes",
      "Statistics and probability",
    ],
    curriculum: [
      { module: "Algebra", topics: ["Real Numbers", "Polynomials", "Quadratic Equations", "Progressions"] },
      { module: "Geometry", topics: ["Coordinate Geometry", "Triangles", "Circles", "Constructions"] },
      {
        module: "Trigonometry",
        topics: ["Trigonometric Ratios", "Complementary Angles", "Trigonometric Identities", "Applications"],
      },
      { module: "Mensuration", topics: ["Areas", "Surface Areas", "Volumes"] },
      { module: "Statistics & Probability", topics: ["Mean, Median, Mode", "Frequency Distribution", "Probability"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 10 - Science",
    category: "Class 10",
    subcategory: "Science",
    description:
      "Science course for Class 10 board exams covering Physics, Chemistry, and Biology with all board exam patterns.",
    price: 2499,
    duration: "16 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 9 Science",
    whatYouWillLearn: [
      "Chemical reactions and equations",
      "Acids, bases, and salts",
      "Metals and non-metals",
      "Light and reflection",
      "Electricity and magnetism",
      "Heredity and evolution",
      "Our environment",
    ],
    curriculum: [
      { module: "Physics", topics: ["Light", "Electricity", "Magnetism", "Motion", "Energy"] },
      {
        module: "Chemistry",
        topics: ["Chemical Reactions", "Acids and Bases", "Metals and Non-metals", "Carbon Compounds"],
      },
      { module: "Biology", topics: ["Life Processes", "Reproduction", "Genetics", "Evolution", "Ecology"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 10 - Social Studies",
    category: "Class 10",
    subcategory: "Social Studies",
    description: "Social Studies course for Class 10 covering History, Geography, Economics, and Political Science.",
    price: 1499,
    duration: "14 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 9 Social Studies",
    whatYouWillLearn: [
      "Modern Indian history",
      "Indian geography",
      "Economics basics",
      "Indian political system",
      "Citizenship and rights",
      "Natural resources",
    ],
    curriculum: [
      { module: "History", topics: ["Colonial India", "Independence Struggle", "Modern India"] },
      { module: "Geography", topics: ["Resources", "Population", "Cities", "Climate"] },
      { module: "Economics", topics: ["Sectors", "Development", "Money", "Trade"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 10 - English",
    category: "Class 10",
    subcategory: "English",
    description: "English course for Class 10 board exams with comprehensive literature and language skills.",
    price: 1499,
    duration: "12 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 9 English",
    whatYouWillLearn: [
      "Grammar and vocabulary",
      "Reading comprehension",
      "Writing skills",
      "Literature analysis",
      "Communication skills",
      "Board exam preparation",
    ],
    curriculum: [
      { module: "Language", topics: ["Grammar", "Vocabulary", "Writing Skills"] },
      { module: "Literature", topics: ["Poetry", "Prose", "Drama"] },
      { module: "Board Exam Skills", topics: ["Comprehension Strategies", "Essay Writing", "Answer Writing"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // Class 11
  {
    title: "Class 11 - Physics",
    category: "Class 11",
    subcategory: "Physics",
    description:
      "Advanced physics course for Class 11 covering mechanics, thermodynamics, and waves with JEE preparation focus.",
    price: 2999,
    duration: "18 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 10 Physics and Mathematics",
    whatYouWillLearn: [
      "Kinematics and dynamics",
      "Work, energy, and power",
      "Gravitation",
      "Simple harmonic motion",
      "Waves and sound",
      "Thermal properties",
      "Kinetic theory of gases",
    ],
    curriculum: [
      { module: "Mechanics", topics: ["Motion", "Forces", "Momentum", "Collisions", "Energy", "Gravity"] },
      { module: "Thermodynamics", topics: ["Heat", "Temperature", "Laws of Thermodynamics"] },
      { module: "Waves", topics: ["Wave Motion", "Sound", "Musical Instruments"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 11 - Chemistry",
    category: "Class 11",
    subcategory: "Chemistry",
    description:
      "Advanced chemistry course for Class 11 covering organic, inorganic, and physical chemistry with competitive exam focus.",
    price: 2999,
    duration: "18 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 10 Chemistry",
    whatYouWillLearn: [
      "Atomic structure and periodic table",
      "Chemical bonding",
      "States of matter",
      "Thermodynamics",
      "Equilibrium",
      "Redox reactions",
      "Organic chemistry basics",
    ],
    curriculum: [
      {
        module: "Physical Chemistry",
        topics: ["Atomic Structure", "Chemical Bonding", "States of Matter", "Thermodynamics"],
      },
      { module: "Inorganic Chemistry", topics: ["Periodic Table", "Metals and Non-metals", "Coordination Compounds"] },
      { module: "Organic Chemistry", topics: ["Hydrocarbons", "Functional Groups", "Nomenclature"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 11 - Mathematics",
    category: "Class 11",
    subcategory: "Mathematics",
    description:
      "Advanced mathematics course for Class 11 covering trigonometry, calculus, and algebra with JEE preparation.",
    price: 2999,
    duration: "18 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 10 Mathematics",
    whatYouWillLearn: [
      "Sets and relations",
      "Trigonometric functions",
      "Algebra of complex numbers",
      "Sequences and series",
      "Permutations and combinations",
      "Binomial theorem",
      "Limits and derivatives",
    ],
    curriculum: [
      { module: "Trigonometry", topics: ["Trigonometric Functions", "Identities", "Equations"] },
      { module: "Algebra", topics: ["Sets", "Relations", "Complex Numbers", "Sequences"] },
      { module: "Calculus", topics: ["Limits", "Continuity", "Derivatives", "Applications"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 11 - Biology",
    category: "Class 11",
    subcategory: "Biology",
    description:
      "Advanced biology course for Class 11 covering cell biology, genetics, and ecology with NEET preparation focus.",
    price: 2999,
    duration: "18 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 10 Biology",
    whatYouWillLearn: [
      "Cell: structure and function",
      "Biomolecules",
      "Cell division",
      "Plant physiology",
      "Animal physiology",
      "Human health and disease",
      "Photosynthesis and respiration",
    ],
    curriculum: [
      { module: "Cell Biology", topics: ["Cell Structure", "Organelles", "Cell Division", "Biomolecules"] },
      { module: "Physiology", topics: ["Plant Physiology", "Animal Physiology", "Nutrition", "Transport"] },
      { module: "Genetics & Health", topics: ["Reproduction", "Genetics Basics", "Health and Disease", "Immunity"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // Class 12
  {
    title: "Class 12 - Physics",
    category: "Class 12",
    subcategory: "Physics",
    description:
      "Advanced physics course for Class 12 board exams covering electricity, magnetism, and modern physics.",
    price: 3499,
    duration: "20 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 11 Physics",
    whatYouWillLearn: [
      "Electrostatics and current electricity",
      "Magnetism and electromagnetic induction",
      "Alternating current",
      "Electromagnetic waves",
      "Optics and wave optics",
      "Modern physics",
      "Atomic and nuclear physics",
    ],
    curriculum: [
      {
        module: "Electricity and Magnetism",
        topics: ["Electrostatics", "Current Electricity", "Magnetism", "Electromagnetic Induction"],
      },
      { module: "Optics", topics: ["Ray Optics", "Wave Optics", "Interference", "Diffraction"] },
      { module: "Modern Physics", topics: ["Photoelectric Effect", "Atoms", "Nuclei", "Semiconductors"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 12 - Chemistry",
    category: "Class 12",
    subcategory: "Chemistry",
    description:
      "Advanced chemistry course for Class 12 covering solid state, electrochemistry, and organic chemistry reactions.",
    price: 3499,
    duration: "20 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 11 Chemistry",
    whatYouWillLearn: [
      "Solid state chemistry",
      "Solutions and colligative properties",
      "Electrochemistry",
      "Chemical kinetics",
      "Surface chemistry",
      "General principles and processes",
      "Organic chemistry mechanisms",
    ],
    curriculum: [
      { module: "Physical Chemistry", topics: ["Solid State", "Solutions", "Electrochemistry", "Kinetics"] },
      {
        module: "Inorganic Chemistry",
        topics: ["P-block Elements", "D-block Elements", "F-block Elements", "Coordination Chemistry"],
      },
      {
        module: "Organic Chemistry",
        topics: ["Organic Reactions", "Mechanisms", "Synthesis", "Polymers", "Biomolecules"],
      },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 12 - Mathematics",
    category: "Class 12",
    subcategory: "Mathematics",
    description:
      "Advanced mathematics course for Class 12 board exams and competitive exams covering calculus, vectors, and 3D geometry.",
    price: 3499,
    duration: "20 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 11 Mathematics",
    whatYouWillLearn: [
      "Inverse trigonometric functions",
      "Matrices and determinants",
      "Continuity and differentiability",
      "Applications of derivatives",
      "Integrals and applications",
      "Vector algebra",
      "3D geometry",
      "Linear programming",
    ],
    curriculum: [
      {
        module: "Calculus",
        topics: ["Derivatives", "Applications of Derivatives", "Integrals", "Differential Equations"],
      },
      { module: "Algebra & Vectors", topics: ["Matrices", "Determinants", "Vectors", "3D Geometry"] },
      { module: "Probability", topics: ["Permutations", "Combinations", "Probability", "Distribution"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Class 12 - Biology",
    category: "Class 12",
    subcategory: "Biology",
    description:
      "Advanced biology course for Class 12 board exams covering genetics, evolution, and ecology with NEET focus.",
    price: 3499,
    duration: "20 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 11 Biology",
    whatYouWillLearn: [
      "Reproduction in organisms",
      "Genetics and inheritance",
      "Molecular basis of inheritance",
      "Evolution",
      "Human health and diseases",
      "Strategies for enhancement",
      "Microbes and their applications",
    ],
    curriculum: [
      {
        module: "Genetics",
        topics: ["Reproduction", "Mendelian Genetics", "Molecular Basis of Inheritance", "Mutations"],
      },
      { module: "Evolution & Ecology", topics: ["Evolution", "Human Evolution", "Biodiversity", "Conservation"] },
      { module: "Applied Biology", topics: ["Biotechnology", "Health and Disease", "Immunology"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // JEE
  {
    title: "JEE Main - Physics",
    category: "JEE",
    subcategory: "Physics",
    description:
      "Comprehensive JEE Main physics course with all topics and mock tests. Designed by expert faculty with 15+ years experience in JEE preparation.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Physics",
    whatYouWillLearn: [
      "Mechanics - Advanced level",
      "Thermodynamics and waves",
      "Electricity and magnetism",
      "Optics and modern physics",
      "Problem-solving strategies",
      "Time management for exams",
    ],
    curriculum: [
      {
        module: "Mechanics",
        topics: ["Kinematics", "Dynamics", "Circular Motion", "Work-Energy", "Collisions", "Gravity"],
      },
      { module: "Electromagnetism", topics: ["Electrostatics", "Current", "Magnetism", "EMI", "AC"] },
      { module: "Optics & Modern", topics: ["Ray Optics", "Wave Optics", "Atomic Physics", "Nuclear Physics"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "JEE Main - Chemistry",
    category: "JEE",
    subcategory: "Chemistry",
    description: "Comprehensive JEE Main chemistry course covering physical, organic, and inorganic chemistry.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Chemistry",
    whatYouWillLearn: [
      "Chemical equilibrium",
      "Redox reactions and electrochemistry",
      "Organic reaction mechanisms",
      "Coordination chemistry",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Physical Chemistry", topics: ["Thermodynamics", "Equilibrium", "Kinetics", "Electrochemistry"] },
      { module: "Organic Chemistry", topics: ["Hydrocarbons", "Reactions", "Mechanisms", "Synthesis"] },
      { module: "Inorganic Chemistry", topics: ["s,p,d,f blocks", "Coordination", "Qualitative Analysis"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "JEE Main - Mathematics",
    category: "JEE",
    subcategory: "Mathematics",
    description: "Comprehensive JEE Main mathematics course with advanced problem-solving techniques.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Mathematics",
    whatYouWillLearn: [
      "Advanced calculus",
      "Coordinate geometry",
      "Vector and 3D geometry",
      "Complex numbers and quadratic equations",
      "Advanced techniques",
    ],
    curriculum: [
      { module: "Calculus", topics: ["Limits", "Continuity", "Derivatives", "Integration", "Differential Equations"] },
      { module: "Geometry & Vectors", topics: ["Coordinate Geometry", "Vectors", "3D Geometry", "Complex Numbers"] },
      {
        module: "Algebra & Trigonometry",
        topics: ["Quadratic Equations", "Sequences", "Permutations", "Trigonometry"],
      },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "JEE Advanced - Physics",
    category: "JEE",
    subcategory: "Physics",
    description: "Advanced physics course for JEE Advanced with highest difficulty level problems and concepts.",
    price: 5999,
    duration: "28 weeks",
    courseLevel: "Advanced",
    prerequisites: "JEE Main Physics",
    whatYouWillLearn: [
      "Advanced mechanics problems",
      "Thermal physics",
      "Experimental physics",
      "Multi-concept problems",
      "Advanced problem-solving",
    ],
    curriculum: [
      { module: "Advanced Mechanics", topics: ["Rotation", "Rigid Bodies", "Fluids", "Oscillations"] },
      { module: "Waves & Thermodynamics", topics: ["Wave Mechanics", "Sound", "Heat Engines"] },
      { module: "Electricity & Optics", topics: ["Advanced E&M", "Optics", "Modern Physics"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "JEE Advanced - Chemistry",
    category: "JEE",
    subcategory: "Chemistry",
    description: "Advanced chemistry course for JEE Advanced covering difficult concepts and reactions.",
    price: 5999,
    duration: "28 weeks",
    courseLevel: "Advanced",
    prerequisites: "JEE Main Chemistry",
    whatYouWillLearn: [
      "Advanced organic synthesis",
      "Analytical chemistry",
      "Complex reactions",
      "Structure determination",
      "Multi-step synthesis",
    ],
    curriculum: [
      { module: "Advanced Organic", topics: ["Multi-step Synthesis", "Mechanisms", "Spectroscopy"] },
      { module: "Advanced Inorganic", topics: ["Transition Metals", "Structure and Bonding", "Qualitative Analysis"] },
      { module: "Physical Chemistry", topics: ["Kinetics", "Electrochemistry", "Thermodynamics"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "JEE Advanced - Mathematics",
    category: "JEE",
    subcategory: "Mathematics",
    description: "Advanced mathematics course for JEE Advanced with complex problem-solving and advanced techniques.",
    price: 5999,
    duration: "28 weeks",
    courseLevel: "Advanced",
    prerequisites: "JEE Main Mathematics",
    whatYouWillLearn: [
      "Advanced calculus and analysis",
      "Complex coordinate geometry",
      "Advanced vector methods",
      "Functional equations",
      "Advanced problem-solving",
    ],
    curriculum: [
      { module: "Analysis", topics: ["Limits & Continuity", "Derivatives", "Integration", "Series"] },
      { module: "Geometry", topics: ["Advanced Coordinate", "Vectors", "3D", "Transformations"] },
      { module: "Algebra", topics: ["Equations", "Inequalities", "Functions", "Complex Numbers"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // NEET
  {
    title: "NEET - Physics",
    category: "NEET",
    subcategory: "Physics",
    description: "Comprehensive physics course for NEET exam preparation covering all topics from Class 11 and 12.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Physics",
    whatYouWillLearn: [
      "Mechanics for NEET",
      "Heat and thermodynamics",
      "Waves and sound",
      "Electricity and magnetism",
      "Optics and modern physics",
      "NEET exam strategies",
    ],
    curriculum: [
      { module: "Mechanics", topics: ["Kinematics", "Forces", "Work-Energy", "Circular Motion", "Gravity"] },
      { module: "Thermodynamics", topics: ["Heat", "Temperature", "Thermodynamics Laws", "Kinetic Theory"] },
      { module: "Waves & Electricity", topics: ["Waves", "Sound", "Electrostatics", "Magnetism", "Optics"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "NEET - Chemistry",
    category: "NEET",
    subcategory: "Chemistry",
    description:
      "Comprehensive chemistry course for NEET covering inorganic and organic chemistry with focus on reactions.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Chemistry",
    whatYouWillLearn: [
      "Periodic table and inorganic chemistry",
      "Organic chemistry reactions",
      "Chemical bonding and structure",
      "Redox reactions",
      "Solutions and equilibrium",
      "NEET exam patterns",
    ],
    curriculum: [
      { module: "Inorganic", topics: ["Periodic Table", "Bonding", "Metals", "Coordination", "Salts"] },
      { module: "Organic", topics: ["Hydrocarbons", "Reactions", "Functional Groups", "Biomolecules"] },
      { module: "Physical", topics: ["Kinetics", "Equilibrium", "Electrochemistry", "Thermodynamics"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "NEET - Biology",
    category: "NEET",
    subcategory: "Biology",
    description: "Comprehensive biology course for NEET covering botany, zoology, and human physiology.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Biology",
    whatYouWillLearn: [
      "Cell and molecular biology",
      "Genetics and evolution",
      "Plant physiology and reproduction",
      "Animal physiology",
      "Human health and immunity",
      "Ecology and conservation",
      "NEET exam strategies",
    ],
    curriculum: [
      { module: "Cell & Genetics", topics: ["Cell Structure", "Cell Division", "Genetics", "Molecular Biology"] },
      {
        module: "Physiology",
        topics: ["Plant Physiology", "Animal Physiology", "Nutrition", "Transport", "Respiration"],
      },
      { module: "Human Biology", topics: ["Reproduction", "Development", "Health", "Immunity", "Evolution"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // AIIMS Paramedical
  {
    title: "AIIMS Paramedical - Physics",
    category: "AIIMS Paramedical",
    subcategory: "Physics",
    description: "Complete physics course for AIIMS Paramedical entrance exams.",
    price: 3999,
    duration: "12 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Physics",
    whatYouWillLearn: ["Mechanics", "Electromagnetism", "Optics", "Modern physics", "Problem-solving techniques"],
    curriculum: [
      {
        module: "Mechanics",
        topics: ["Kinematics", "Dynamics", "Circular Motion", "Work-Energy", "Collisions", "Gravity"],
      },
      { module: "Electromagnetism", topics: ["Electrostatics", "Current", "Magnetism", "EMI", "AC"] },
      { module: "Optics", topics: ["Ray Optics", "Wave Optics", "Optical Instruments"] },
      { module: "Modern Physics", topics: ["Atomic Physics", "Nuclear Physics", "Semiconductors"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "AIIMS Paramedical - Chemistry",
    category: "AIIMS Paramedical",
    subcategory: "Chemistry",
    description: "Complete chemistry course for AIIMS Paramedical entrance exams.",
    price: 3999,
    duration: "12 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Chemistry",
    whatYouWillLearn: [
      "Physical chemistry",
      "Organic chemistry",
      "Inorganic chemistry",
      "Qualitative analysis",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Physical Chemistry", topics: ["Thermodynamics", "Equilibrium", "Kinetics", "Electrochemistry"] },
      { module: "Organic Chemistry", topics: ["Hydrocarbons", "Reactions", "Mechanisms", "Synthesis"] },
      { module: "Inorganic Chemistry", topics: ["s,p,d,f blocks", "Coordination", "Qualitative Analysis"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "AIIMS Paramedical - Biology",
    category: "AIIMS Paramedical",
    subcategory: "Biology",
    description: "Complete biology course for AIIMS Paramedical entrance exams.",
    price: 3999,
    duration: "12 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Biology",
    whatYouWillLearn: [
      "Cell biology",
      "Genetics",
      "Human health and disease",
      "Microbes and their applications",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Cell Biology", topics: ["Cell Structure", "Cell Division", "Biomolecules"] },
      { module: "Genetics", topics: ["Reproduction", "Mendelian Genetics", "Molecular Basis of Inheritance"] },
      { module: "Human Health", topics: ["Diseases", "Immunity", "Nutrition"] },
      { module: "Microbes", topics: ["Microbial World", "Applications"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // Nursing Entrance
  {
    title: "Nursing Entrance - Physics",
    category: "Nursing Entrance",
    subcategory: "Physics",
    description: "Physics course for Nursing entrance exams.",
    price: 2999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic Physics Knowledge",
    whatYouWillLearn: [
      "Basic concepts of physics",
      "Motion",
      "Force and energy",
      "Sound and light",
      "Electricity and magnetism",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Basic Physics", topics: ["Units and Measurements", "Motion", "Force", "Energy"] },
      { module: "Sound & Light", topics: ["Sound Waves", "Light Waves", "Reflection", "Refraction"] },
      { module: "Electricity & Magnetism", topics: ["Electrostatics", "Current Electricity", "Magnetism"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Nursing Entrance - Chemistry",
    category: "Nursing Entrance",
    subcategory: "Chemistry",
    description: "Chemistry course for Nursing entrance exams.",
    price: 2999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic Chemistry Knowledge",
    whatYouWillLearn: [
      "Basic concepts of chemistry",
      "Atomic structure",
      "Chemical reactions",
      "Acids and bases",
      "Organic compounds",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Basic Chemistry", topics: ["Matter", "Atoms", "Molecules"] },
      { module: "Chemical Reactions", topics: ["Types", "Equations", "Stoichiometry"] },
      { module: "Organic Chemistry", topics: ["Hydrocarbons", "Functional Groups", "Nomenclature"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Nursing Entrance - Biology",
    category: "Nursing Entrance",
    subcategory: "Biology",
    description: "Biology course for Nursing entrance exams.",
    price: 2999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic Biology Knowledge",
    whatYouWillLearn: [
      "Cell biology",
      "Genetics",
      "Human health and disease",
      "Microbes and their applications",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Cell Biology", topics: ["Cell Structure", "Cell Division", "Biomolecules"] },
      { module: "Genetics", topics: ["Reproduction", "Mendelian Genetics", "Molecular Basis of Inheritance"] },
      { module: "Human Health", topics: ["Diseases", "Immunity", "Nutrition"] },
      { module: "Microbes", topics: ["Microbial World", "Applications"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // CUET (UG)
  {
    title: "CUET (UG) - Mathematics",
    category: "CUET (UG)",
    subcategory: "Mathematics",
    description: "Mathematics course for CUET Undergraduate entrance exam.",
    price: 3499,
    duration: "16 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Mathematics",
    whatYouWillLearn: ["Algebra", "Geometry", "Calculus", "Probability", "Statistics", "Problem-solving techniques"],
    curriculum: [
      { module: "Algebra", topics: ["Sets", "Relations", "Complex Numbers", "Matrices"] },
      { module: "Geometry", topics: ["Coordinate Geometry", "Vectors", "3D Geometry"] },
      { module: "Calculus", topics: ["Limits", "Derivatives", "Integrals", "Applications"] },
      { module: "Probability & Statistics", topics: ["Probability", "Statistics", "Distributions"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "CUET (UG) - Physics",
    category: "CUET (UG)",
    subcategory: "Physics",
    description: "Physics course for CUET Undergraduate entrance exam.",
    price: 3499,
    duration: "16 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Physics",
    whatYouWillLearn: ["Mechanics", "Electromagnetism", "Optics", "Modern physics", "Problem-solving techniques"],
    curriculum: [
      {
        module: "Mechanics",
        topics: ["Kinematics", "Dynamics", "Circular Motion", "Work-Energy", "Collisions", "Gravity"],
      },
      { module: "Electromagnetism", topics: ["Electrostatics", "Current", "Magnetism", "EMI", "AC"] },
      { module: "Optics", topics: ["Ray Optics", "Wave Optics", "Optical Instruments"] },
      { module: "Modern Physics", topics: ["Atomic Physics", "Nuclear Physics", "Semiconductors"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "CUET (UG) - Chemistry",
    category: "CUET (UG)",
    subcategory: "Chemistry",
    description: "Chemistry course for CUET Undergraduate entrance exam.",
    price: 3499,
    duration: "16 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Chemistry",
    whatYouWillLearn: [
      "Physical chemistry",
      "Organic chemistry",
      "Inorganic chemistry",
      "Qualitative analysis",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Physical Chemistry", topics: ["Thermodynamics", "Equilibrium", "Kinetics", "Electrochemistry"] },
      { module: "Organic Chemistry", topics: ["Hydrocarbons", "Reactions", "Mechanisms", "Synthesis"] },
      { module: "Inorganic Chemistry", topics: ["s,p,d,f blocks", "Coordination", "Qualitative Analysis"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "CUET (UG) - Biology",
    category: "CUET (UG)",
    subcategory: "Biology",
    description: "Biology course for CUET Undergraduate entrance exam.",
    price: 3499,
    duration: "16 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Biology",
    whatYouWillLearn: [
      "Cell biology",
      "Genetics",
      "Human health and disease",
      "Microbes and their applications",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Cell Biology", topics: ["Cell Structure", "Cell Division", "Biomolecules"] },
      { module: "Genetics", topics: ["Reproduction", "Mendelian Genetics", "Molecular Basis of Inheritance"] },
      { module: "Human Health", topics: ["Diseases", "Immunity", "Nutrition"] },
      { module: "Microbes", topics: ["Microbial World", "Applications"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // TGT/PGT Preparation
  {
    title: "TGT Preparation - Science",
    category: "TGT/PGT",
    subcategory: "Science",
    description: "Complete TGT (Trained Graduate Teacher) preparation course.",
    price: 4499,
    duration: "20 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Science",
    whatYouWillLearn: [
      "Science teaching methodologies",
      "Classroom management",
      "Assessment techniques",
      "Curriculum development",
      "Problem-solving strategies",
    ],
    curriculum: [
      {
        module: "Teaching Methodologies",
        topics: ["Classroom Management", "Assessment Techniques", "Curriculum Development"],
      },
      { module: "Science Content", topics: ["Physics", "Chemistry", "Biology"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "PGT Preparation - Physics",
    category: "TGT/PGT",
    subcategory: "Physics",
    description: "PGT (Post Graduate Teacher) Physics preparation course.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Physics",
    whatYouWillLearn: [
      "Advanced physics concepts",
      "Teaching strategies",
      "Problem-solving techniques",
      "Laboratory management",
      "Curriculum development",
    ],
    curriculum: [
      { module: "Advanced Physics", topics: ["Quantum Mechanics", "Special Relativity", "Nuclear Physics"] },
      {
        module: "Teaching Strategies",
        topics: ["Classroom Management", "Assessment Techniques", "Curriculum Development"],
      },
      { module: "Laboratory Management", topics: ["Safety Measures", "Equipment Handling", "Experiment Design"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "PGT Preparation - Chemistry",
    category: "TGT/PGT",
    subcategory: "Chemistry",
    description: "PGT (Post Graduate Teacher) Chemistry preparation course.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Chemistry",
    whatYouWillLearn: [
      "Advanced chemistry concepts",
      "Teaching strategies",
      "Problem-solving techniques",
      "Laboratory management",
      "Curriculum development",
    ],
    curriculum: [
      { module: "Advanced Chemistry", topics: ["Organic Reactions", "Inorganic Compounds", "Physical Chemistry"] },
      {
        module: "Teaching Strategies",
        topics: ["Classroom Management", "Assessment Techniques", "Curriculum Development"],
      },
      { module: "Laboratory Management", topics: ["Safety Measures", "Equipment Handling", "Experiment Design"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "PGT Preparation - Mathematics",
    category: "TGT/PGT",
    subcategory: "Mathematics",
    description: "PGT (Post Graduate Teacher) Mathematics preparation course.",
    price: 4999,
    duration: "24 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Mathematics",
    whatYouWillLearn: [
      "Advanced mathematics concepts",
      "Teaching strategies",
      "Problem-solving techniques",
      "Laboratory management",
      "Curriculum development",
    ],
    curriculum: [
      { module: "Advanced Mathematics", topics: ["Calculus", "Algebra", "Geometry", "Probability"] },
      {
        module: "Teaching Strategies",
        topics: ["Classroom Management", "Assessment Techniques", "Curriculum Development"],
      },
      { module: "Laboratory Management", topics: ["Safety Measures", "Equipment Handling", "Experiment Design"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // KVS/NVS Preparation
  {
    title: "KVS/NVS - Teaching Methodology",
    category: "KVS/NVS",
    subcategory: "Teaching",
    description: "Teaching methodology and pedagogy for KVS/NVS exams.",
    price: 3999,
    duration: "14 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Basic Teaching Knowledge",
    whatYouWillLearn: [
      "Classroom management",
      "Assessment techniques",
      "Curriculum development",
      "Pedagogical skills",
      "Problem-solving techniques",
    ],
    curriculum: [
      {
        module: "Teaching Methodologies",
        topics: ["Classroom Management", "Assessment Techniques", "Curriculum Development"],
      },
      { module: "Pedagogical Skills", topics: ["Lesson Planning", "Instructional Strategies", "Student Engagement"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "KVS/NVS - Subject Specialization",
    category: "KVS/NVS",
    subcategory: "Subject",
    description: "Subject specialization course for KVS/NVS teaching exams.",
    price: 3999,
    duration: "14 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 12 Science",
    whatYouWillLearn: [
      "Advanced science concepts",
      "Teaching strategies",
      "Problem-solving techniques",
      "Laboratory management",
      "Curriculum development",
    ],
    curriculum: [
      { module: "Advanced Science", topics: ["Physics", "Chemistry", "Biology"] },
      {
        module: "Teaching Strategies",
        topics: ["Classroom Management", "Assessment Techniques", "Curriculum Development"],
      },
      { module: "Laboratory Management", topics: ["Safety Measures", "Equipment Handling", "Experiment Design"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // NET & GATE
  {
    title: "NET - Chemical Sciences",
    category: "NET & GATE",
    subcategory: "Chemical Sciences",
    description: "NET (National Eligibility Test) preparation for Chemical Sciences.",
    price: 5999,
    duration: "28 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Chemistry",
    whatYouWillLearn: [
      "Advanced physical chemistry",
      "Advanced organic chemistry",
      "Advanced inorganic chemistry",
      "Research methodologies",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Physical Chemistry", topics: ["Thermodynamics", "Equilibrium", "Kinetics", "Electrochemistry"] },
      { module: "Organic Chemistry", topics: ["Advanced Reactions", "Mechanisms", "Synthesis"] },
      { module: "Inorganic Chemistry", topics: ["Transition Metals", "Structure and Bonding", "Qualitative Analysis"] },
      { module: "Research Methodologies", topics: ["Design", "Execution", "Analysis"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "GATE - Life Sciences",
    category: "NET & GATE",
    subcategory: "Life Sciences",
    description: "GATE (Graduate Aptitude Test) preparation for Life Sciences.",
    price: 5999,
    duration: "28 weeks",
    courseLevel: "Advanced",
    prerequisites: "Class 12 Biology",
    whatYouWillLearn: [
      "Advanced cell biology",
      "Advanced genetics",
      "Advanced human health",
      "Research methodologies",
      "Problem-solving techniques",
    ],
    curriculum: [
      { module: "Cell Biology", topics: ["Advanced Cell Structure", "Cell Division", "Biomolecules"] },
      { module: "Genetics", topics: ["Advanced Mendelian Genetics", "Molecular Basis of Inheritance"] },
      { module: "Human Health", topics: ["Advanced Diseases", "Advanced Immunity", "Advanced Nutrition"] },
      { module: "Research Methodologies", topics: ["Design", "Execution", "Analysis"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // KYPS Olympiad
  {
    title: "KYPS Olympiad - Science",
    category: "KYPS Olympiad",
    subcategory: "Science",
    description: "KYPS (Kishore Vaigyanik Protsahan Yojana) Olympiad preparation.",
    price: 2999,
    duration: "12 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 10 Science",
    whatYouWillLearn: [
      "Advanced science concepts",
      "Olympiad problem-solving techniques",
      "Research methodologies",
      "Critical thinking",
    ],
    curriculum: [
      { module: "Advanced Science", topics: ["Physics", "Chemistry", "Biology"] },
      { module: "Olympiad Problem Solving", topics: ["Strategies", "Techniques", "Mock Tests"] },
      { module: "Research Methodologies", topics: ["Design", "Execution", "Analysis"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "KYPS Olympiad - Mathematics",
    category: "KYPS Olympiad",
    subcategory: "Mathematics",
    description: "KYPS Mathematics Olympiad preparation course.",
    price: 2999,
    duration: "12 weeks",
    courseLevel: "Intermediate",
    prerequisites: "Class 10 Mathematics",
    whatYouWillLearn: [
      "Advanced mathematics concepts",
      "Olympiad problem-solving techniques",
      "Research methodologies",
      "Critical thinking",
    ],
    curriculum: [
      { module: "Advanced Mathematics", topics: ["Calculus", "Algebra", "Geometry", "Probability"] },
      { module: "Olympiad Problem Solving", topics: ["Strategies", "Techniques", "Mock Tests"] },
      { module: "Research Methodologies", topics: ["Design", "Execution", "Analysis"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },

  // Foreign Language Courses
  {
    title: "German Language - Beginner",
    category: "Foreign Languages",
    subcategory: "German",
    description: "German language course for beginners.",
    price: 1999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic Language Knowledge",
    whatYouWillLearn: [
      "Basic German grammar",
      "Vocabulary building",
      "Reading comprehension",
      "Writing skills",
      "Listening and speaking",
    ],
    curriculum: [
      { module: "Grammar", topics: ["Nouns", "Verbs", "Adjectives"] },
      { module: "Vocabulary", topics: ["Basic Words", "Phrases", "Greetings"] },
      { module: "Listening & Speaking", topics: ["Basic Conversations", "Listening Skills", "Speaking Skills"] },
      { module: "Reading & Writing", topics: ["Basic Texts", "Writing Practice", "Comprehension"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "French Language - Beginner",
    category: "Foreign Languages",
    subcategory: "French",
    description: "French language course for beginners.",
    price: 1999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic Language Knowledge",
    whatYouWillLearn: [
      "Basic French grammar",
      "Vocabulary building",
      "Reading comprehension",
      "Writing skills",
      "Listening and speaking",
    ],
    curriculum: [
      { module: "Grammar", topics: ["Nouns", "Verbs", "Adjectives"] },
      { module: "Vocabulary", topics: ["Basic Words", "Phrases", "Greetings"] },
      { module: "Listening & Speaking", topics: ["Basic Conversations", "Listening Skills", "Speaking Skills"] },
      { module: "Reading & Writing", topics: ["Basic Texts", "Writing Practice", "Comprehension"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
  {
    title: "Japanese Language - Beginner",
    category: "Foreign Languages",
    subcategory: "Japanese",
    description: "Japanese language course for beginners.",
    price: 1999,
    duration: "10 weeks",
    courseLevel: "Beginner",
    prerequisites: "Basic Language Knowledge",
    whatYouWillLearn: [
      "Basic Japanese grammar",
      "Vocabulary building",
      "Reading comprehension",
      "Writing skills",
      "Listening and speaking",
    ],
    curriculum: [
      { module: "Grammar", topics: ["Particles", "Verbs", "Adjectives"] },
      { module: "Vocabulary", topics: ["Basic Words", "Phrases", "Greetings"] },
      { module: "Listening & Speaking", topics: ["Basic Conversations", "Listening Skills", "Speaking Skills"] },
      { module: "Reading & Writing", topics: ["Basic Texts", "Writing Practice", "Comprehension"] },
    ],
    courseIncludes: {
      videos: true,
      liveLectures: true,
      pdfs: true,
      quizzes: true,
      assignments: true,
      certificates: true,
    },
  },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost:27017/edutech")
    console.log("MongoDB connected for seeding")

    // Clear existing data
    await User.deleteMany({})
    await Course.deleteMany({})
    console.log("Existing data cleared")

    // Create expert faculty with enhanced qualifications
    const expertFaculty = new User({
      name: "Dr. Abhishek Jha",
      email: "abhishekjha2707@gmail.com",
      password: "faculty123",
      role: "faculty",
      phone: "9876543211",
      qualifications: [
        "Ph.D in Chemistry",
        "NET & GATE Qualified",
        "Ex Lecturer Government College",
        "15+ Years Teaching Experience",
        "IIT Delhi Alumni",
      ],
      experience: "15+ years of teaching experience in Chemistry and competitive exam preparation",
      specialization: ["Chemistry", "JEE", "NEET", "NET", "GATE"],
      achievements: [
        "Mentored 5000+ successful students",
        "100+ IIT selections",
        "50+ AIIMS selections",
        "Expert in competitive exam patterns",
      ],
    })

    const student = new User({
      name: "Ajay Jha",
      email: "ajha97575@gmail.com",
      password: "password123",
      role: "student",
      phone: "9876543210",
    })

    const admin = new User({
      name: "Abhishek",
      email: "abhishek.flyanytrip@gmail.com",
      password: "admin123",
      role: "admin",
      phone: "9876543212",
    })

    await expertFaculty.save()
    console.log("Expert faculty created with enhanced qualifications")

    await student.save()
    console.log("Student user created with hashed password")

    await admin.save()
    console.log("Admin user created with hashed password")

    const coursesToCreate = courseData.map((course) => ({
      ...course,
      faculty: expertFaculty._id,
      assignedTo: expertFaculty.email,
      totalEnrolled: Math.floor(Math.random() * 100) + 20, // Increased enrollment numbers
      instructorQualification: "Ph.D, NET & GATE Qualified, 15+ Years Experience",
    }))

    await Course.insertMany(coursesToCreate)
    console.log(`Courses created and assigned to expert faculty (${coursesToCreate.length} courses)`)

    console.log("✓ Seeding completed successfully!")
    console.log("✓ All data saved to MongoDB")
    process.exit(0)
  } catch (error) {
    console.error("✗ Seeding failed:", error.message)
    process.exit(1)
  }
}

seed()
